const date1 = new Date()
const date2 = new Date(19999)
const date3 = new Date("2011/3/10")
const date4 = new Date(2021,3,10,2,40,10)

console.log(date1)
console.log(date2)
console.log(date3)
console.log(date4)

console.log(date1.getDate())
console.log(date1.getDay())
console.log(date1.getMonth())
console.log(date1.getTime())
console.log(date1.getSeconds())
console.log(date1.getHours())
console.log(date1.getMinutes())
console.log(date1.getUTCFullYear())
console.log(date1.getUTCDate())
console.log(date1.getUTCDay())
console.log(date1.getUTCHours())
console.log(date1.getUTCMilliseconds())
console.log(date1.getUTCMinutes())
console.log(date1.setDate(4))
console.log(new Date(date1.setDate(4)))
console.log(new Date(date1.setDate(4)))
console.log(new Date(date1.setFullYear(2022,4,1)))
console.log(new Date(date1.setMinutes(866)))
console.log(date1.toDateString())
console.log(date1.toJSON())
console.log(date1.toTimeString())
console.log(date1.toTimeString())
console.log(date1.valueOf())//return milliseconds